#include "pch.h"
#include "window/MenuOverlayHost.h"
#include "window/WindowManager.h"
#include "core/WebViewContext.h"
#include "api/BridgeCore.h"
#include "webview/WebViewHost.h"
#include "utils/GuidUtils.h"
#include "window/MenuOverlayPage.inl"

// ============================================
// Self-drawn menu overlay host (renderer + submenu + keyboard nav).
// Page sources: src/window/menu-overlay/ ; generated by scripts/gen_menu_overlay_page.mjs
// ============================================

namespace {
    std::wstring BuildMenuOverlayHtml() {
        return BuildMenuOverlayHtmlFromSources();
    }
}

// ---------- MenuOverlayWindow ----------

void MenuOverlayWindow::OnWebViewReady() {
    PopupWindow::OnWebViewReady();
    if (!readyHtml_.empty()) {
        NavigateToString(readyHtml_);
    }
    if (webViewReadyCallback_) {
        webViewReadyCallback_();
    }
}

// ---------- MenuOverlayHost ----------

MenuOverlayHost& MenuOverlayHost::GetInstance() {
    static MenuOverlayHost instance;
    return instance;
}

bool MenuOverlayHost::EnsureCreated() {
    PFC_ASSERT(core_api::is_main_thread());
    if (overlay_ && overlayHwnd_ && IsWindow(overlayHwnd_)) {
        return true;
    }

    overlay_ = std::make_unique<MenuOverlayWindow>();
    overlay_->SetReadyHtml(BuildMenuOverlayHtml());

    PopupWindow::CreateParams params;
    params.url = "";
    params.width = 16;
    params.height = 16;
    params.x = 0;
    params.y = 0;
    params.title = "MenuOverlay";
    params.resizable = false;
    params.frame = false;
    params.transparent = true;
    params.alwaysOnTop = true;
    params.showInTaskbar = false;
    params.beforeClose = false;

    params.hasBehavior = true;
    params.behavior = {
        {"noActivate", false},
        {"owner", "none"},
        {"showInTaskbar", false},
        {"showInAltTab", false},
        {"keepVisibleOnShowDesktop", true}
    };
    params.hasBackdropPolicy = true;
    // 自绘菜单系统级亚克力（DWM backdrop）。overlay 已 transparent=true，默认不透明的
    // .fb-menu 背景（#2b2b2b）仍完全遮住亚克力 → 默认视觉零回归；前端把 .fb-menu 背景
    // 改半透明后才透出亚克力。active/inactive 均用 acrylic：菜单弹出期间宿主窗口可能不持
    // 前台激活（noActivate 行为 / 任务栏交互），inactive 同样保亚克力，避免失焦瞬间掉成纯色。
    // 仅改 backdrop 材质，未触碰 transparent 标志与窗口几何 / 定位 / 不-resize 逻辑
    // （ADR-018 浮任务栏不压暗 / ADR-019 防闪烁固定窗）。注意：此 overlay 由 tray
    // （ContentSized 小窗）与 menu.show（FullscreenOverlay 全屏透明窗）共用，backdrop 在此
    // 一次性设定；全屏透明区在 acrylic 下的观感建议真机验证。
    params.backdropPolicy = {
        {"activeEffect", "acrylic"},
        {"inactiveEffect", "acrylic"},
        {"darkMode", true}
    };

    HWND mainHwnd = core_api::get_main_window();
    HWND hwnd = overlay_->Create(params, kOverlayWindowId, mainHwnd);
    if (!hwnd) {
        overlay_.reset();
        overlayHwnd_ = nullptr;
        console::print("[MenuOverlayHost] EnsureCreated failed: Create returned null");
        return false;
    }
    overlayHwnd_ = hwnd;

    overlay_->SetSuppressLifecycleBroadcast(true);
    overlay_->SetMenuDismissCallback([](const std::string& reason) {
        MenuOverlayHost::GetInstance().OnRootDismissRequested(reason);
    });

    ShowWindow(overlayHwnd_, SW_HIDE);
    console::print("[MenuOverlayHost] overlay created and hidden (pooled)");
    return true;
}

std::string MenuOverlayHost::Show(const json& items, int screenX, int screenY,
                                  SelectSink onSelect, DismissSink onDismiss,
                                  const MenuShowOptions& opts, ValueSink onValue) {
    PFC_ASSERT(core_api::is_main_thread());
    if (!EnsureCreated()) {
        return std::string();
    }

    // 交错策略 (R3)：已有菜单在显示【或处于退场动画期】时，先强制立即收尾旧菜单，再写入新 sink，
    // 杜绝新 sink 被误用于旧菜单的 dismiss。退场期 visible_&&closing_ 时，Hide("replaced") 会被
    // if(closing_) return 挡掉，旧菜单不会被收回 → 池化单窗会出现旧菜单淡出同时显示新菜单 (R1)。
    // 故直接 ForceHideImmediate 强制同步收尾（绕过 animate 判定），旧 sink/ownerMode 分发 dismiss。
    if (visible_ || closing_) {
        ForceHideImmediate();
    }
    selectSink_ = std::move(onSelect);
    dismissSink_ = std::move(onDismiss);
    valueSink_ = std::move(onValue);
    ownerMode_ = static_cast<bool>(selectSink_) || static_cast<bool>(dismissSink_)
              || static_cast<bool>(valueSink_);
    windowModel_ = opts.windowModel;  // 窗口几何模型（与 ownerMode_ 正交）
    overlayModel_ = opts.overlayModel;  // DOM 输入模型（与 windowModel_ / ownerMode_ 正交）
    currentCss_ = opts.css;            // 前端样式接管（S-CSS）：本次 show 的前端 CSS（每次 show 覆盖即复位）
    currentCssReplace_ = opts.cssReplace;  // replace 模式开关（默认 false = override 叠加）
    currentCloseAnimationMs_ = opts.closeAnimationMs;  // 退场动画时长（0=立即隐藏不动画，零回归）
    currentBackdrop_ = opts.backdrop;
    currentBackdropDarkMode_ = opts.backdropDarkMode;

    POINT pt{ screenX, screenY };
    HMONITOR mon = MonitorFromPoint(pt, MONITOR_DEFAULTTONEAREST);
    MONITORINFO mi{};
    mi.cbSize = sizeof(mi);
    RECT work{ 0, 0, GetSystemMetrics(SM_CXSCREEN), GetSystemMetrics(SM_CYSCREEN) };
    RECT full = work;
    if (mon && GetMonitorInfo(mon, &mi)) {
        work = mi.rcWork;
        full = mi.rcMonitor;
    }

    currentItems_ = json::array();
    currentZones_ = json::array();
    // Assign an opaque single-use token per actionable node and (re)build the
    // token table BEFORE the renderer pulls state. currentItems_/currentZones_
    // are mutated in place: each node gains a `_token`, internal `_origin` /
    // `_builtinAction` are stripped. select / valueChanged resolve only through
    // this table. The generator checks the GUID HRESULT; the table retries on
    // collision. If a unique token cannot be assigned, the build fails
    // transactionally and we abort the Show — never expose a partial token set.
    auto guidGen = []() -> std::optional<std::string> {
        GUID guid{};
        if (FAILED(CoCreateGuid(&guid))) return std::nullopt;
        return GuidUtils::GuidToString(guid);
    };
    // `ownerMode_` is set only by the tray-owned C++ path. Public `menu.show`
    // has no owner sinks and therefore cannot promote private JSON action fields.
    const bool trustInternalActionFields = ownerMode_;
    bool tokensOk = false;
    if (overlayModel_ == MenuOverlayModel::TrayZones) {
        currentZones_ = items.is_array() ? items : json::array();
        tokensOk = tokenTable_.RebuildZones(currentZones_, guidGen, trustInternalActionFields);
    } else {
        currentItems_ = items.is_array() ? items : json::array();
        tokensOk = tokenTable_.Rebuild(currentItems_, guidGen, trustInternalActionFields);
    }
    if (!tokensOk) {
        tokenTable_.Clear();
        currentItems_ = json::array();
        currentZones_ = json::array();
        selectSink_ = nullptr;
        dismissSink_ = nullptr;
        valueSink_ = nullptr;
        ownerMode_ = false;
        console::print("[MenuOverlayHost] Show aborted: opaque token assignment failed");
        return std::string();
    }

    // A pooled submenu may still be visible from the preceding session. Hide
    // it before the new root receives focus so the two HWNDs never overlap
    // across menu generations.
    HideSubmenuWindow(false, false, false);

    if (windowModel_ == MenuWindowModel::ContentSized) {
        // ContentSized：先以临时尺寸在光标附近显示（渲染器 opacity:0 测量），
        // 收到 menu.__ready 后由 OnContentMeasured 定位到内容尺寸（rcMonitor 边界，可压任务栏）。
        measureGate_.Begin();
        placedGeometry_.reset();
        contentVirtualOrigin_ = POINT{};
        openSubmenuVirtualRect_.reset();
        openSubmenuParentToken_.clear();
        lastSubmenuPanelSequence_ = 0;
        pendingSubmenuPanelSequence_.reset();
        overlay_->ClearContentRegion();
        pendingAnchor_ = pt;
        anchorClientX_ = 0;   // 内容窗：菜单贴客户区原点，渲染器 placeRoot 退化
        anchorClientY_ = 0;
        const int workW = work.right - work.left;
        const int workH = work.bottom - work.top;
        const int tmpW = workW < 480 ? workW : 480;
        const int tmpH = workH < 720 ? workH : 720;
        // 临时窗放屏幕外测量（off-screen + opacity:0 双保险），由 OnContentMeasured 再移到光标处，
        // 彻底消除“先在上方固定高度出现、测量后跳到光标”的可见跳变（用户反馈 bug1）。
        SetWindowPos(overlayHwnd_, HWND_TOPMOST, -32000, -32000, tmpW, tmpH, SWP_NOACTIVATE);
    } else {
        // FullscreenOverlay（现状）：铺满工作区。
        measureGate_.Cancel();
        placedGeometry_.reset();
        contentVirtualOrigin_ = POINT{};
        openSubmenuVirtualRect_.reset();
        openSubmenuParentToken_.clear();
        lastSubmenuPanelSequence_ = 0;
        pendingSubmenuPanelSequence_.reset();
        overlay_->ClearContentRegion();
        const int w = work.right - work.left;
        const int h = work.bottom - work.top;
        anchorClientX_ = screenX - work.left;
        anchorClientY_ = screenY - work.top;
        SetWindowPos(overlayHwnd_, HWND_TOPMOST, work.left, work.top, w, h, SWP_NOACTIVATE);
    }

    ShowWindow(overlayHwnd_, SW_SHOW);
    SetForegroundWindow(overlayHwnd_);
    SetWindowPos(overlayHwnd_, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);

    // 运行时按本次 config 应用 DWM 系统背景：池化 overlay 被 tray（ContentSized）与
    // menu.show（FullscreenOverlay）共用，逐 show 覆盖。须在 ShowWindow 之后调，避开
    // “隐藏窗口设 backdrop 不初始化合成”的坑（EnsureCreated 的 acrylic 仅作创建默认）。
    // menu.show 走默认 opts（backdrop=acrylic）= 与原创建期行为等价；失败仅忽略。
    if (overlay_) {
        std::string bderr;
        overlay_->UpdateBackdropPolicy(
            json{ {"activeEffect", opts.backdrop}, {"inactiveEffect", opts.backdrop}, {"darkMode", opts.backdropDarkMode} },
            bderr);
    }
    if (overlay_->IsWebViewReady()) {
        if (auto* wv = overlay_->GetWebView()) {
            RECT rc{};
            GetClientRect(overlayHwnd_, &rc);
            wv->SetVisible(true);
            wv->Resize(rc);
            if (auto* ctrl = wv->GetController()) {
                ctrl->NotifyParentWindowPositionChanged();
                ctrl->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);  // 让 WebView 内容获键盘焦点（菜单可即时键盘导航）
            }
        }
    }

    currentMenuId_ = "menu-" + std::to_string(++showSeq_);
    visible_ = true;
    showTick_ = GetTickCount64();
    ArmWatchdog();
    if (windowModel_ == MenuWindowModel::ContentSized) {
        ArmMeasureTimer();  // 测量回报兜底
    }

    if (overlay_->IsWebViewReady() && overlay_->GetBridge()) {
        overlay_->GetBridge()->EmitEvent("menu:show", { {"menuId", currentMenuId_} });
    }

    console::printf("[MenuOverlayHost] Show id=%s items=%d model=%s anchorClient=(%d,%d)",
                    currentMenuId_.c_str(), (int)currentItems_.size(),
                    windowModel_ == MenuWindowModel::ContentSized ? "content" : "fullscreen",
                    anchorClientX_, anchorClientY_);
    return currentMenuId_;
}

void MenuOverlayHost::Hide(const std::string& reason) {
    if (reason == "blur" && visible_ && (GetTickCount64() - showTick_) < 250) {
        return;
    }
    if (!visible_) {
        return;
    }
    if (closing_) {
        // 已在退场动画期：幂等吞掉重入 / 多源 dismiss（blur/outside/timeout 等），
        // 由 close-timer → FinalizeHide 收尾 (R1：防淡出期重复触发 / 重入)。
        return;
    }

    // The root can fade, but the independent DWM-backed submenu must never
    // remain visible or interactive during that fade. Clear its pending/open
    // state before either root-close branch; no focus restore or root renderer
    // notification is allowed because this is a whole-menu close, not a child
    // return. A late child-ready callback is rejected by the closing/state gates.
    const bool windowOk = overlayHwnd_ && IsWindow(overlayHwnd_);
    const auto closePolicy = menu_overlay_geometry::ResolveRootClosePolicy(
        reason, windowOk, currentCloseAnimationMs_);
    if (closePolicy.hideSubmenuImmediately) {
        HideSubmenuWindow(closePolicy.restoreRootFocus, closePolicy.notifyRootRenderer,
                          closePolicy.clearSubmenuStateImmediately);
    }

    if (closePolicy.animateRoot) {
        // 进入 Closing：visible_ 仍 true；发内部事件 menu:__hide 通知渲染器播退场；ArmCloseTimer
        // 延迟到 close-timer 收尾。此刻【不】SW_HIDE、【不】分发 dismiss（留到 FinalizeHide）。
        // 注意：select 的 selectSink_ 已在 OnSelect 里先于 Hide("select") 派发（动作不被动画延迟，R7）。
        closing_ = true;
        pendingCloseReason_ = reason;
        if (overlay_ && overlay_->IsWebViewReady() && overlay_->GetBridge()) {
            overlay_->GetBridge()->EmitEvent("menu:__hide", { {"menuId", currentMenuId_} });  // 内部事件（overlay 私有 bridge→渲染器）；:__ 前缀=codegen 不进公共 events.ts
        }
        ArmCloseTimer(currentCloseAnimationMs_);
        console::printf("[MenuOverlayHost] Hide(animate) id=%s reason=%s ms=%d",
                        currentMenuId_.c_str(), reason.c_str(), currentCloseAnimationMs_);
        return;
    }

    // 立即路径（现状同步隐藏，零回归）：未开动画 / replaced / timeout / measure_timeout / 窗口失效等。
    FinalizeHide(reason);
}

void MenuOverlayHost::OnDismissRequested(HWND caller, const std::string& reason) {
    if (!visible_ || closing_) {
        return;
    }
    if (caller && caller == submenuHwnd_ && (reason == "escape" || reason == "submenu-left")) {
        HideSubmenuWindow(true, true);
        return;
    }
    Hide(reason);
}

void MenuOverlayHost::FinalizeHide(const std::string& reason) {
    // 两段式 Hide 的同步收尾（立即路径 / close-timer 收尾共用）。
    // 先捕获并复位状态（务必在 ShowWindow 之前，R2）：ShowWindow(SW_HIDE) 会同步触发
    // WM_KILLFOCUS → dismiss 回调 → 重入 Hide。若状态后置清理，重入会先清掉 ownerMode_，
    // 外层继续时误判为非 owner 而泄漏 menu:dismiss。先置 visible_=false 且 closing_=false 让重入早退。
    visible_ = false;
    closing_ = false;
    measureGate_.Cancel();
    placedGeometry_.reset();
    contentVirtualOrigin_ = POINT{};
    HideSubmenuWindow(false);
    lastSubmenuPanelSequence_ = 0;
    pendingSubmenuPanelSequence_.reset();
    pendingCloseReason_.clear();
    const std::string closedId = currentMenuId_;
    currentMenuId_.clear();
    currentItems_ = json::array();
    currentZones_ = json::array();
    overlayModel_ = MenuOverlayModel::LegacyItems;
    tokenTable_.Clear();             // opaque tokens are single-use per show; invalidate now
    currentCss_.clear();              // 前端样式接管（S-CSS）：本次 show 结束复位，防泄漏到下次
    currentCssReplace_ = false;

    // owner-mode：dismiss 改走 sink（tray 默认无 sink = 原生菜单关闭不发事件），
    // 不发公共 menu:dismiss；menu.* 普通模式维持现状。
    // sink 生命周期：本次 show 结束即释放（避免泄漏到下次 menu.show）。
    const bool wasOwnerMode = ownerMode_;
    DismissSink dismissSink = dismissSink_;
    selectSink_ = nullptr;
    dismissSink_ = nullptr;
    valueSink_ = nullptr;
    ownerMode_ = false;

    KillWatchdog();
    KillMeasureTimer();
    KillCloseTimer();
    if (overlay_) {
        overlay_->ClearContentRegion();
    }
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        ShowWindow(overlayHwnd_, SW_HIDE);
    }

    if (wasOwnerMode) {
        if (dismissSink) {
            try { dismissSink(reason); } catch (...) {}
        }
    } else {
        BridgeCore::GetInstance().EmitEvent("menu:dismiss", {
            {"menuId", closedId},
            {"reason", reason}
        });
    }
    console::printf("[MenuOverlayHost] FinalizeHide id=%s reason=%s owner=%d",
                    closedId.c_str(), reason.c_str(), (int)wasOwnerMode);
}

void MenuOverlayHost::ForceHideImmediate() {
    // Show 取消挂起关闭复用 (R3)：绕过 animate 判定，直接同步收尾。退场期 visible_&&closing_ 时，
    // 新 Hide("replaced") 会被 if(closing_) return 挡掉，故 Show 不能依赖 Hide("replaced")。
    // 用 "replaced" 收尾（与历史 Show 调 Hide("replaced") 行为一致；tray owner-mode 无 dismiss sink，
    // reason 仅记录用；menu.show 因 closeAnimationMs=0 永不进 Closing，此处恒等于历史立即替换路径）。
    if (!visible_ && !closing_) {
        return;
    }
    FinalizeHide("replaced");
}

void MenuOverlayHost::OnSelect(const std::string& token) {
    // Reject during the exit animation (closing_): visible_ is still true then,
    // and the token set is not cleared until final teardown, so without this a
    // rapid repeat click could re-run the same action.
    if (!visible_ || closing_) {
        return;
    }
    auto action = tokenTable_.ResolveSelect(token);
    if (!action.has_value()) {
        return;   // unknown / expired token, disabled item, submenu parent, or value control
    }
    // First accepted select wins: invalidate the whole token set NOW so a
    // re-entrant / rapid second select resolves to nothing.
    tokenTable_.Clear();
    const std::string menuId = currentMenuId_;
    if (ownerMode_) {
        // owner-mode：选中改走 sink（→ tray:menuItemClicked），按可信 origin 路由
        if (selectSink_) {
            try { selectSink_(*action); } catch (...) {}
        }
    } else {
        // 公共 menu.show：仅发索引里的 publicId（永不回 token）
        BridgeCore::GetInstance().EmitEvent("menu:select", {
            {"menuId", menuId},
            {"itemId", action->publicId}
        });
    }
    console::printf("[MenuOverlayHost] Select id=%s item=%s owner=%d",
                    menuId.c_str(), action->publicId.c_str(), (int)ownerMode_);
    Hide("select");
}

void MenuOverlayHost::OnValueChanged(const std::string& token, int value) {
    // 富控件（rating/slider/segmented）值变更：解析 token → 按控件类型校验值 → 经
    // valueSink_ 回报，【不关闭菜单】。无 sink / 非法 token / 越界值静默忽略。
    // 退场动画期（closing_）拒绝，避免淡出中改值。
    if (!visible_ || closing_) {
        return;
    }
    auto publicId = tokenTable_.ResolveValue(token, value);
    if (!publicId.has_value()) {
        return;   // not a value control, out-of-range value, disabled item, or unknown token
    }
    if (valueSink_) {
        try { valueSink_(*publicId, value); } catch (...) {}
    }
    console::printf("[MenuOverlayHost] ValueChanged item=%s value=%d owner=%d",
                    publicId->c_str(), value, (int)ownerMode_);
}

bool MenuOverlayHost::OnContentMeasured(const menu_overlay_geometry::MeasureReport& report) {
    PFC_ASSERT(core_api::is_main_thread());
    if (!visible_ || closing_ || windowModel_ != MenuWindowModel::ContentSized ||
        !measureGate_.IsAwaiting()) {
        return false;
    }
    const bool hasSubmenu = HasFirstLevelSubmenu();
    if (!menu_overlay_geometry::IsValidMeasureReport(report, hasSubmenu)) {
        return false;
    }

    HMONITOR mon = MonitorFromPoint(pendingAnchor_, MONITOR_DEFAULTTONEAREST);
    MONITORINFO mi{};
    mi.cbSize = sizeof(mi);
    RECT full{ 0, 0, GetSystemMetrics(SM_CXSCREEN), GetSystemMetrics(SM_CYSCREEN) };
    RECT work = full;
    if (mon && GetMonitorInfo(mon, &mi)) {
        full = mi.rcMonitor;   // rcMonitor 边界 → 可压任务栏
        work = mi.rcWork;
    }

    const auto placement = menu_overlay_geometry::ComputePlacement(
        report, hasSubmenu, work.right - work.left, work.bottom - work.top);
    if (!placement.has_value()) {
        return false;
    }
    const int virtualW = placement->viewportW;
    const int virtualH = placement->viewportH;

    // 定位：根底贴光标（上展贴托盘），根左=光标 x。窗口高=根高 → 窗口底=光标 y（不超屏，无垂直偏移）。
    int x = pendingAnchor_.x;
    int y = pendingAnchor_.y - virtualH;
    if (x + virtualW > full.right) x = full.right - virtualW;    // 右预留超屏 → 左移整组根/子窗口
    if (x < full.left) x = full.left;
    if (y < full.top) y = full.top;

    contentVirtualOrigin_ = POINT{x, y};
    // The root is a tight real HWND. Do not reserve an invisible native slot
    // and do not depend on SetWindowRgn to hide a DWM system backdrop: Windows
    // 11 composes DWMSBT_TRANSIENTWINDOW across the HWND rectangle.
    if (!ApplyRootContentWindow(*placement)) {
        console::printf("[MenuOverlayHost] ContentMeasured root window failed id=%s",
                        currentMenuId_.c_str());
        return false;
    }
    if (!measureGate_.TryConsume(true)) {
        if (overlay_) overlay_->ClearContentRegion();
        return false;
    }
    KillMeasureTimer();
    placedGeometry_ = placement;
    SyncWebViewToClient(overlay_.get(), overlayHwnd_);
    if (overlay_->IsWebViewReady() && overlay_->GetBridge()) {
        overlay_->GetBridge()->EmitEvent("menu:__placed", {
            {"menuId", currentMenuId_},
            {"first", true},
            {"geometry", BuildRootGeometryJson(*placement)}
        });  // overlay-private bridge event; not part of public SDK events
    }
    console::printf("[MenuOverlayHost] ContentMeasured root id=%s win=(%d,%d) pos=(%d,%d) virtual=(%d,%d)",
                    currentMenuId_.c_str(), placement->rootSlotW, placement->rootVisibleH,
                    x, y + placement->rootTop, virtualW, virtualH);
    return true;
}

bool MenuOverlayHost::OnSubmenuPanelChanged(
    const menu_overlay_geometry::SubmenuPanelRequest& request,
    const std::string& parentToken) {
    // Root close clears pending/open child state before a possible fade. Never
    // accept renderer hover reports while closing: an old ready/hover callback
    // must not resurrect a submenu HWND after its root started disappearing.
    if (!visible_ || closing_) {
        return false;
    }
    const auto update = menu_overlay_geometry::EvaluateSubmenuPanelUpdate(
        windowModel_ == MenuWindowModel::ContentSized, placedGeometry_, request);
    const auto newestAppliedOrPending = pendingSubmenuPanelSequence_.value_or(lastSubmenuPanelSequence_);
    if (!update.accepted || !placedGeometry_.has_value()) {
        return false;
    }
    if (!request.visible) {
        if (!menu_overlay_geometry::IsNewerSubmenuPanelSequence(newestAppliedOrPending, request.sequence)) {
            return false;
        }
        HideSubmenuWindow(false);
        lastSubmenuPanelSequence_ = request.sequence;
        pendingSubmenuPanelSequence_.reset();
        return true;
    }
    if (!update.submenuWindow.has_value() || parentToken.empty() ||
        !FindSubmenuItems(parentToken).has_value()) {
        return false;
    }
    // A retry for the same still-pending renderer frame is accepted; a stale
    // older sequence remains rejected. This is needed while a newly created
    // child WebView reaches its first hidden ready state.
    if (request.sequence != newestAppliedOrPending &&
        !menu_overlay_geometry::IsNewerSubmenuPanelSequence(newestAppliedOrPending, request.sequence)) {
        return false;
    }
    openSubmenuVirtualRect_ = update.submenuWindow;
    openSubmenuParentToken_ = parentToken;
    pendingSubmenuPanelSequence_ = request.sequence;
    if (!EnsureSubmenuCreated()) return false;
    // Each open first refreshes the hidden renderer state. It acknowledges the
    // existing `menu.__submenuPanel` endpoint with `ready:true` before this HWND is made visible, avoiding a blank
    // DWM-material flash and stale items when hover switches siblings quickly.
    HideSubmenuWindow(false, false, false);
    if (submenuOverlay_ && submenuOverlay_->IsWebViewReady() && submenuOverlay_->GetBridge()) {
        submenuOverlay_->GetBridge()->EmitEvent("menu:show", {{"menuId", currentMenuId_}});
    }
    return true;
}

bool MenuOverlayHost::OnSubmenuSurfaceReady(HWND caller, const std::string& parentToken) {
    if (caller != submenuHwnd_ || !visible_ || closing_ || !openSubmenuVirtualRect_.has_value() ||
        parentToken.empty() || parentToken != openSubmenuParentToken_ ||
        !pendingSubmenuPanelSequence_.has_value()) {
        return false;
    }
    if (!ShowSubmenuWindow(*openSubmenuVirtualRect_, openSubmenuParentToken_)) return false;
    lastSubmenuPanelSequence_ = *pendingSubmenuPanelSequence_;
    pendingSubmenuPanelSequence_.reset();
    if (overlay_ && overlay_->IsWebViewReady() && overlay_->GetBridge()) {
        overlay_->GetBridge()->EmitEvent("menu:__submenuOpened", {{"menuId", currentMenuId_}});
    }
    return true;
}

json MenuOverlayHost::GetMenuStateJson(HWND caller) const {
    const bool isSubmenuSurface = caller && caller == submenuHwnd_;
    json st = {
        {"visible", visible_},
        {"menuId", currentMenuId_},
        {"anchorX", anchorClientX_},
        {"anchorY", anchorClientY_},
        // 窗口几何模型：渲染器据此分支（contentSized = 去 #block + placeRoot 退化 + 测量回报）。
        {"windowModel", isSubmenuSurface ? "submenu" :
            (windowModel_ == MenuWindowModel::ContentSized ? "contentSized" : "fullscreen")},
        {"surface", isSubmenuSurface ? "submenu" : "root"},
        // Overlay DOM 输入模型（显式，禁止由 windowModel 猜测）。
        {"overlayModel", overlayModel_ == MenuOverlayModel::TrayZones ? "trayZones" : "legacyItems"},
        {"layoutMode", overlayModel_ == MenuOverlayModel::TrayZones ? "zones" : "flat"},
        // 前端样式接管（S-CSS）：css = 前端注入样式字符串（写入 <style id="fb-user">）；
        // cssReplace = true 时 replace 模式（禁用默认样式，仅留 fb-user+fb-protected），false = override 叠加。
        {"css", currentCss_},
        {"cssReplace", currentCssReplace_}
    };
    if (isSubmenuSurface) {
        st["overlayModel"] = "legacyItems";
        st["layoutMode"] = "flat";
        st["zones"] = json::array();
        st["items"] = FindSubmenuItems(openSubmenuParentToken_).value_or(json::array());
        st["parentToken"] = openSubmenuParentToken_;
        if (openSubmenuVirtualRect_.has_value()) {
            st["geometry"] = {
                {"viewportW", openSubmenuVirtualRect_->w},
                {"viewportH", openSubmenuVirtualRect_->h},
                {"rootSlotW", openSubmenuVirtualRect_->w},
                {"subSlotW", 0},
                {"rootTop", 0}
            };
        }
    } else if (overlayModel_ == MenuOverlayModel::TrayZones) {
        st["zones"] = currentZones_;
        st["items"] = json::array();  // zones model: items unused
    } else {
        st["items"] = currentItems_;
        st["zones"] = json::array();
    }
    return st;
}

bool MenuOverlayHost::IsOverlayCaller(HWND caller) const {
    // The overlay's renderer messages arrive with _callerHwnd == overlayHwnd_
    // (WebViewPanel::HandleWebMessage injects the window hwnd_). Any other window
    // — or a call before the overlay exists — is rejected.
    return menu_action::IsSameOverlayWindow(caller, overlayHwnd_) ||
        menu_action::IsSameOverlayWindow(caller, submenuHwnd_);
}

bool MenuOverlayHost::IsRootOverlayCaller(HWND caller) const {
    return menu_action::IsSameOverlayWindow(caller, overlayHwnd_);
}

bool MenuOverlayHost::ValidateMenuId(const std::string& menuId) const {
    // Only the currently-visible menu's id is accepted; a stale page report or a
    // forged id from another surface cannot drive select/dismiss/ready/value.
    return menu_action::IsCurrentMenuId(menuId, currentMenuId_, visible_);
}

bool MenuOverlayHost::HasFirstLevelSubmenu() const {
    const auto hasSubmenu = [](const json& items) {
        if (!items.is_array()) return false;
        for (const auto& item : items) {
            if (item.is_object() && item.contains("submenu") &&
                item["submenu"].is_array() && !item["submenu"].empty()) {
                return true;
            }
        }
        return false;
    };
    if (overlayModel_ == MenuOverlayModel::TrayZones) {
        if (!currentZones_.is_array()) return false;
        for (const auto& zone : currentZones_) {
            if (zone.is_object() && zone.contains("items") && hasSubmenu(zone["items"])) {
                return true;
            }
        }
        return false;
    }
    return hasSubmenu(currentItems_);
}

void MenuOverlayHost::Shutdown() {
    KillWatchdog();
    KillMeasureTimer();
    KillCloseTimer();
    visible_ = false;
    closing_ = false;
    measureGate_.Cancel();
    placedGeometry_.reset();
    contentVirtualOrigin_ = POINT{};
    HideSubmenuWindow(false);
    lastSubmenuPanelSequence_ = 0;
    pendingSubmenuPanelSequence_.reset();
    pendingCloseReason_.clear();
    currentMenuId_.clear();
    currentItems_ = json::array();
    currentZones_ = json::array();
    overlayModel_ = MenuOverlayModel::LegacyItems;
    tokenTable_.Clear();
    if (overlay_) {
        overlay_->ClearContentRegion();
        overlay_->Destroy();
        overlay_.reset();
    }
    overlayHwnd_ = nullptr;
    if (submenuOverlay_) {
        submenuOverlay_->Destroy();
        submenuOverlay_.reset();
    }
    submenuHwnd_ = nullptr;
}

bool MenuOverlayHost::ApplyRootContentWindow(const menu_overlay_geometry::Placement& placement) {
    if (!overlayHwnd_ || !IsWindow(overlayHwnd_)) return false;
    const auto root = menu_overlay_geometry::RootWindowExtent(placement);
    if (root.w <= 0 || root.h <= 0) return false;
    if (!SetWindowPos(overlayHwnd_, HWND_TOPMOST,
                      contentVirtualOrigin_.x + root.x, contentVirtualOrigin_.y + root.y,
                      root.w, root.h, SWP_NOACTIVATE)) {
        return false;
    }
    // A tight HWND is the visual contract. Clear any region left from prior
    // pooled shows; the region is retained only for unrelated popup consumers,
    // never as the correctness mechanism for this overlay's DWM backdrop.
    return !overlay_ || overlay_->ClearContentRegion();
}

bool MenuOverlayHost::EnsureSubmenuCreated() {
    if (submenuOverlay_ && submenuHwnd_ && IsWindow(submenuHwnd_)) return true;

    submenuOverlay_ = std::make_unique<MenuOverlayWindow>();
    submenuOverlay_->SetReadyHtml(BuildMenuOverlayHtml());
    submenuOverlay_->SetWebViewReadyCallback([]() {
        MenuOverlayHost::GetInstance().OnSubmenuWebViewReady();
    });
    PopupWindow::CreateParams params;
    params.url = "";
    params.width = 16;
    params.height = 16;
    params.x = -32000;
    params.y = -32000;
    params.title = "MenuOverlaySubmenu";
    params.resizable = false;
    params.frame = false;
    params.transparent = true;
    params.alwaysOnTop = true;
    params.showInTaskbar = false;
    params.beforeClose = false;
    params.hasBehavior = true;
    params.behavior = {
        {"noActivate", false},
        {"owner", "none"},
        {"showInTaskbar", false},
        {"showInAltTab", false},
        {"keepVisibleOnShowDesktop", true}
    };
    params.hasBackdropPolicy = true;
    params.backdropPolicy = {
        {"activeEffect", currentBackdrop_},
        {"inactiveEffect", currentBackdrop_},
        {"darkMode", currentBackdropDarkMode_}
    };
    submenuHwnd_ = submenuOverlay_->Create(params, "__menu_overlay_submenu__", core_api::get_main_window());
    if (!submenuHwnd_) {
        submenuOverlay_.reset();
        return false;
    }
    submenuOverlay_->SetSuppressLifecycleBroadcast(true);
    submenuOverlay_->SetMenuDismissCallback([](const std::string& reason) {
        MenuOverlayHost::GetInstance().OnSubmenuDismissRequested(reason);
    });
    ShowWindow(submenuHwnd_, SW_HIDE);
    return true;
}

bool MenuOverlayHost::ShowSubmenuWindow(const menu_overlay_geometry::Rect& virtualRect,
                                        const std::string& parentToken) {
    if (!submenuOverlay_ || !submenuHwnd_ || !IsWindow(submenuHwnd_) ||
        !submenuOverlay_->IsWebViewReady() || parentToken.empty()) {
        return false;
    }
    if (virtualRect.w <= 0 || virtualRect.h <= 0) return false;
    openSubmenuVirtualRect_ = virtualRect;
    openSubmenuParentToken_ = parentToken;
    // Position and resize while hidden. The caller only reaches this point
    // after the submenu DOM has acknowledged its current token-scoped items.
    // Thus the first DWM-composited visible frame already contains the panel.
    if (!SetWindowPos(submenuHwnd_, HWND_TOPMOST,
                      contentVirtualOrigin_.x + virtualRect.x,
                      contentVirtualOrigin_.y + virtualRect.y,
                      virtualRect.w, virtualRect.h, SWP_NOACTIVATE)) {
        return false;
    }
    if (!submenuOverlay_->ClearContentRegion()) return false;
    std::string backdropError;
    submenuOverlay_->UpdateBackdropPolicy(
        json{{"activeEffect", currentBackdrop_}, {"inactiveEffect", currentBackdrop_},
             {"darkMode", currentBackdropDarkMode_}}, backdropError);
    SyncWebViewToClient(submenuOverlay_.get(), submenuHwnd_);
    openingSubmenu_ = true;
    ShowWindow(submenuHwnd_, SW_SHOW);
    SetForegroundWindow(submenuHwnd_);
    openingSubmenu_ = false;
    SetWindowPos(submenuHwnd_, HWND_TOPMOST, 0, 0, 0, 0,
                 SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
    if (auto* wv = submenuOverlay_->GetWebView()) {
        if (auto* ctrl = wv->GetController()) {
            ctrl->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);
        }
    }
    if (submenuOverlay_->GetBridge()) {
        submenuOverlay_->GetBridge()->EmitEvent("menu:__submenuVisible", {{"menuId", currentMenuId_}});
    }
    return true;
}

void MenuOverlayHost::HideSubmenuWindow(bool restoreRootFocus, bool notifyRoot, bool clearState) {
    if (clearState) {
        openSubmenuVirtualRect_.reset();
        openSubmenuParentToken_.clear();
        pendingSubmenuPanelSequence_.reset();
    }
    if (!submenuHwnd_ || !IsWindow(submenuHwnd_)) return;
    suppressSubmenuDismiss_ = true;
    ShowWindow(submenuHwnd_, SW_HIDE);
    if (restoreRootFocus && visible_ && overlayHwnd_ && IsWindow(overlayHwnd_)) {
        SetForegroundWindow(overlayHwnd_);
        if (overlay_ && overlay_->GetWebView() && overlay_->GetWebView()->GetController()) {
            overlay_->GetWebView()->GetController()->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);
        }
    }
    suppressSubmenuDismiss_ = false;
    if (notifyRoot && overlay_ && overlay_->IsWebViewReady() && overlay_->GetBridge()) {
        overlay_->GetBridge()->EmitEvent("menu:__submenuClosed", {{"menuId", currentMenuId_}});
    }
}

void MenuOverlayHost::OnSubmenuWebViewReady() {
    // The child page's bootstrap pull renders the current token-scoped state
    // and acknowledges `menu.__submenuPanel` with `ready:true`; do not expose
    // a backdrop before then.
}

void MenuOverlayHost::OnRootDismissRequested(const std::string& reason) {
    // Activating the independently hosted submenu deactivates the root HWND.
    // That hand-off is internal, not an outside click and must not close either
    // panel before the submenu receives its first input.
    if (openingSubmenu_ || (openSubmenuVirtualRect_.has_value() && submenuHwnd_ && IsWindow(submenuHwnd_) &&
        GetForegroundWindow() == submenuHwnd_)) {
        return;
    }
    Hide(reason);
}

void MenuOverlayHost::OnSubmenuDismissRequested(const std::string& reason) {
    if (suppressSubmenuDismiss_ || !visible_ || closing_) return;
    if (reason == "escape" || (overlayHwnd_ && GetForegroundWindow() == overlayHwnd_)) {
        HideSubmenuWindow(true, true);
        return;
    }
    Hide(reason);
}

void MenuOverlayHost::SyncWebViewToClient(MenuOverlayWindow* window, HWND hwnd) const {
    if (!window || !hwnd || !IsWindow(hwnd) || !window->IsWebViewReady()) return;
    if (auto* wv = window->GetWebView()) {
        RECT rc{};
        GetClientRect(hwnd, &rc);
        wv->SetVisible(true);
        wv->Resize(rc);
        if (auto* ctrl = wv->GetController()) ctrl->NotifyParentWindowPositionChanged();
    }
}

json MenuOverlayHost::BuildRootGeometryJson(const menu_overlay_geometry::Placement& placement) const {
    return {
        {"viewportW", placement.rootSlotW},
        {"viewportH", placement.rootVisibleH},
        {"rootSlotW", placement.rootSlotW},
        {"subSlotW", placement.subSlotW},
        {"rootTop", 0},
        {"virtualViewportH", placement.viewportH},
        {"virtualRootTop", placement.rootTop}
    };
}

std::optional<json> MenuOverlayHost::FindSubmenuItems(const std::string& parentToken) const {
    if (parentToken.empty()) return std::nullopt;
    const auto findInItems = [&parentToken](const json& items) -> std::optional<json> {
        if (!items.is_array()) return std::nullopt;
        for (const auto& item : items) {
            if (item.is_object() && item.value("_token", std::string()) == parentToken &&
                item.contains("submenu") && item["submenu"].is_array() && !item["submenu"].empty()) {
                return item["submenu"];
            }
        }
        return std::nullopt;
    };
    if (overlayModel_ == MenuOverlayModel::TrayZones) {
        for (const auto& zone : currentZones_) {
            if (zone.is_object() && zone.contains("items")) {
                if (auto items = findInItems(zone["items"])) return items;
            }
        }
        return std::nullopt;
    }
    return findInItems(currentItems_);
}

void MenuOverlayHost::ArmWatchdog() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        SetTimer(overlayHwnd_, kWatchdogTimerId, kWatchdogTimeoutMs, &MenuOverlayHost::WatchdogTimerProc);
    }
}

void MenuOverlayHost::KillWatchdog() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        KillTimer(overlayHwnd_, kWatchdogTimerId);
    }
}

void CALLBACK MenuOverlayHost::WatchdogTimerProc(HWND /*hwnd*/, UINT /*msg*/, UINT_PTR idEvent, DWORD /*elapsed*/) {
    if (idEvent != kWatchdogTimerId) {
        return;
    }
    MenuOverlayHost::GetInstance().Hide("timeout");
}

void MenuOverlayHost::ArmMeasureTimer() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        SetTimer(overlayHwnd_, kMeasureTimerId, kMeasureTimeoutMs, &MenuOverlayHost::MeasureTimerProc);
    }
}

void MenuOverlayHost::KillMeasureTimer() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        KillTimer(overlayHwnd_, kMeasureTimerId);
    }
}

void CALLBACK MenuOverlayHost::MeasureTimerProc(HWND /*hwnd*/, UINT /*msg*/, UINT_PTR idEvent, DWORD /*elapsed*/) {
    if (idEvent != kMeasureTimerId) {
        return;
    }
    // ContentSized 测量回报兜底：超时未收 menu.__ready 即关闭，避免卡在临时尺寸。
    auto& self = MenuOverlayHost::GetInstance();
    if (self.measureGate_.IsAwaiting()) {
        self.Hide("measure_timeout");
    }
}

void MenuOverlayHost::ArmCloseTimer(int ms) {
    if (!overlayHwnd_ || !IsWindow(overlayHwnd_)) {
        return;
    }
    if (ms < 0) ms = 0;
    if (ms > kCloseAnimationMaxMs) ms = kCloseAnimationMaxMs;   // 防御性 clamp（解析层已 clamp 0..1000）
    SetTimer(overlayHwnd_, kCloseTimerId, static_cast<UINT>(ms), &MenuOverlayHost::CloseTimerProc);
}

void MenuOverlayHost::KillCloseTimer() {
    if (overlayHwnd_ && IsWindow(overlayHwnd_)) {
        KillTimer(overlayHwnd_, kCloseTimerId);
    }
}

void CALLBACK MenuOverlayHost::CloseTimerProc(HWND /*hwnd*/, UINT /*msg*/, UINT_PTR idEvent, DWORD /*elapsed*/) {
    if (idEvent != kCloseTimerId) {
        return;
    }
    // 退场动画收尾：退场时长到期后做与立即路径等价的同步收尾。reason 用进入 Closing 时记录的原始值。
    auto& self = MenuOverlayHost::GetInstance();
    if (self.closing_) {
        self.FinalizeHide(self.pendingCloseReason_);
    }
}